// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-workers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_workers_default = defineTool({
  name: "list_workers",
  title: "List employees",
  description: "List employees (workers) visible to the signed-in user. Respects the app's role and department permissions.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional substring to match against full name, matricule, or CIN."),
    limit: z.number().int().positive().optional().describe("Max number of rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("workers").select("id, full_name, matricule, cin, position, department, phone, is_active").limit(limit ?? 50);
    if (search && search.length > 0) {
      const like = `%${search}%`;
      q = q.or(`full_name.ilike.${like},matricule.ilike.${like},cin.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { workers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-worker.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_worker_default = defineTool2({
  name: "get_worker",
  title: "Get employee",
  description: "Fetch a single employee by id, matricule, or CIN.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Employee UUID."),
    matricule: z2.string().trim().optional().describe("Employee matricule."),
    cin: z2.string().trim().optional().describe("Employee CIN (national ID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, matricule, cin }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !matricule && !cin) {
      return {
        content: [{ type: "text", text: "Provide id, matricule, or cin." }],
        isError: true
      };
    }
    let q = supabaseForUser2(ctx).from("workers").select("*").limit(1);
    if (id) q = q.eq("id", id);
    else if (matricule) q = q.eq("matricule", matricule);
    else if (cin) q = q.eq("cin", cin);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { worker: data }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_documents_default = defineTool3({
  name: "list_documents",
  title: "List documents",
  description: "List HR documents (contracts, bons de sortie, avertissements, etc.). Optionally filter by worker or type.",
  inputSchema: {
    worker_id: z3.string().uuid().optional().describe("Filter to a single employee."),
    document_type: z3.string().trim().optional().describe("Filter by document type (e.g. contract, bon_sortie, avertissement)."),
    limit: z3.number().int().positive().optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ worker_id, document_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("documents").select("id, title, document_type, worker_id, created_at, status").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (worker_id) q = q.eq("worker_id", worker_id);
    if (document_type) q = q.eq("document_type", document_type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-absences.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_absences_default = defineTool4({
  name: "list_absences",
  title: "List absences",
  description: "List absence records, optionally filtered by month (YYYY-MM) or worker.",
  inputSchema: {
    worker_id: z4.string().uuid().optional().describe("Filter to a single employee."),
    month: z4.string().regex(/^\d{4}-\d{2}$/).optional().describe("Filter by month in YYYY-MM format. Defaults to no filter."),
    limit: z4.number().int().positive().optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ worker_id, month, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("absences").select("*").order("absence_date", { ascending: false }).limit(limit ?? 100);
    if (worker_id) q = q.eq("worker_id", worker_id);
    if (month) {
      const [y, m] = month.split("-").map(Number);
      const start = new Date(Date.UTC(y, m - 1, 1)).toISOString().slice(0, 10);
      const end = new Date(Date.UTC(y, m, 1)).toISOString().slice(0, 10);
      q = q.gte("absence_date", start).lt("absence_date", end);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { absences: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in user calling this MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xtkzwmepptbpuutepkum";
var mcp_default = defineMcp({
  name: "rh-doc-gen-mcp",
  title: "Rh Doc Gen (ERCM)",
  version: "0.1.0",
  instructions: "Tools for the ERCM Rh Doc Gen HR app. Look up employees, HR documents (contracts, bons de sortie, avertissements), and absences for the signed-in user. All calls respect the user's role and department permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_workers_default, get_worker_default, list_documents_default, list_absences_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
