ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'CNC';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'VISITEUR';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'UNITE_ONE';
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'UNITE_TWO';